Issue 111 Selbstverwaltung
Campus-Consult/MemberManager pull request #129
Opened 2022-04-26 18:23 UTC by Alfer-Star

#111 Selbstverwaltungsfeature auf der Startseite.
Wenn der Nutzer noch nicht in der Datenbank hinterlegt ist, erhält er die Möglichkeit sich zu erstellen.

2022-04-26 18:55 UTC, olohr requested changes

2022-04-26 18:55 UTC, olohr commented on src/WebUI/ClientApp/src/app/home/home.component.ts
> +    '.userinfo { display: flex; align-items: flex-start; justify-content: space-between;}',
Shouldn't that be in the css file angular creates automatically?

2022-04-26 18:55 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-self-managed/member-self-managed.component.html
> +    <ng-container *ngIf="memberData && !isEditing; else noDataMessage">
Is this how you write if else in angular? Is there not a way to keep the content of the else branch close to the if, so the flow is easier to follow?

2022-04-26 18:55 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-self-managed/member-self-managed.component.ts
> +  private convertCreateFormIntoCommand(formResult: any): UpdatePersonCommand {
wrong return type.

This shouldn't compile imo, I think we should update our typescript settings to catch this. Otherwise we don't have any advantages of using typescript

2022-04-26 18:55 UTC, olohr commented on src/WebUI/ClientApp/src/app/shared/components/member-form/member-form.component.ts
> +  @Input() isCreate?: boolean = false;
why is this optional if it has a default?

2022-04-26 18:55 UTC, olohr commented on src/WebUI/ClientApp/src/app/shared/components/member-form/member-form.component.ts
> +  @Input() formDisabled?: boolean;
The default should be false here as well, right? If it's not passed in, it's set to `undefined` and treated as false, would be better to have that explicit imo

2022-04-26 18:55 UTC, olohr commented on src/WebUI/ClientApp/src/app/home/home.component.html
> +    <p *ngIf="isAuthenticated | async">
Does if else work here?

2022-05-03 17:03 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/home/home.component.ts
> +    '.userinfo { display: flex; align-items: flex-start; justify-content: space-between;}',
Normally it does. Bit there wasn´t any.
I was lazy and interested this would work. I will fix this.

2022-05-03 17:08 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/modules/member-management/member-self-managed/member-self-managed.component.html
> +    <ng-container *ngIf="memberData && !isEditing; else noDataMessage">
You can place the else part in ng-template everywhere you want.  
You are right. Keeping it close would make the code much more readable, you would not need to search the else part.
I will fix this.

2022-05-03 17:12 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/shared/components/member-form/member-form.component.ts
> +  @Input() formDisabled?: boolean;
Cannot argue against that.

2022-05-03 17:28 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/modules/member-management/member-self-managed/member-self-managed.component.ts
> +  private convertCreateFormIntoCommand(formResult: any): UpdatePersonCommand {
Fixed
Would  [noEmitOnError](https://www.typescriptlang.org/tsconfig#noEmitOnError) to true help?

2022-05-03 17:29 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/shared/components/member-form/member-form.component.ts
> +  @Input() isCreate?: boolean = false;
Good question. It should not necesssary. Probalby a move of tired me.

2022-05-03 17:38 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/home/home.component.html
> +    <p *ngIf="isAuthenticated | async">
yes, i fixed it.

2022-05-10 15:53 UTC, olohr commented on src/WebUI/ClientApp/src/app/shared/components/member-form/member-form.component.ts
> +  @Input() formDisabled: boolean = true;
This seems to be the wrong default, the entire form is now always disabled for me

2022-05-10 16:03 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-self-managed/member-self-managed.component.ts
> +  private convertCreateFormIntoCommand(formResult: any): UpdatePersonCommand {
No, since typescript compiles fine and doesn't emit an error, I even tried strict mode (which seems to be really garbage when used with angular)

2022-05-10 16:11 UTC, merged