Refactoring Member Details View and Fix Skeleton Loader bei leeren Feldern
Campus-Consult/MemberManager pull request #53
Opened 2021-05-18 17:32 UTC by Alfer-Star

Did some Refactoring, so Skeleton Loader will only display if there no memberDetails data given as Input. #39 

Refactoring:
simplified HMTL View 
display of Label and data is controlled by component

Did test
- by adding an new member without optional data => seklton not displayed
- Skeleton loader are displayed corrrectly, if ng-if in view false (same as data undefined)

2021-05-20 16:33 UTC, olohr requested changes
overall good changes, just a few nitpicks

2021-05-20 16:33 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data/member-data.component.ts
> +  get gender(): string {
this can be simplified
```
  get gender(): string {
    switch (this.memberDetails.gender) {
      case Gender.MALE:
        return "Männlich";
      case Gender.FEMALE:
        return "Weiblich";
      case Gender.DIVERS:
        return "Divers";
      default:
        return "No Gender";
    }
  }
```

2021-05-20 16:33 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data/member-data.component.ts
> +    let value = "";
See above, you can just use returns here.
Also I personally prefer to use curly braces even if there is only one statement in the if block

2021-05-20 16:33 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data/member-data.component.ts
> +    let value: string;
See above

2021-05-25 15:47 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data/member-data.component.ts
> +  get gender(): string {
That implemention was intended, but does not necessarily generate any advantages. I could fix it to make code shorter, but i don't need it would be necessary.
On Work our lead Developer, likes to see this.
Here is an Article whch discusses Single exit point rule and multy exit. If you are interested.
https://medium.com/ncr-edinburgh/early-exit-c86d5f0698ba#:~:text=The%20single%20exit%20point%20rule%20is%20the%20idea%20that%20a,be%20easier%20to%20understand%20right%3F

2021-05-25 15:49 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data/member-data.component.ts
> +    let value = "";
See above. 
Ist Geschmacksache finde ich. :D

2021-05-25 15:49 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data/member-data.component.ts
> +    let value: string;
see above.

2021-06-08 15:33 UTC, merged