Delete Button in Member Detail View
Campus-Consult/MemberManager pull request #86
Opened 2021-09-07 17:30 UTC by Alfer-Star

#72

2021-09-10 19:14 UTC, olohr requested changes

2021-09-10 19:14 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data-sheet.component.ts
> +      this.showLoadingText = undefined;
showLoadingText is typed as `string`, so the linter should complain that you try to assign undefined here. I would prefer using `string | null` as type and assigning null here

2021-09-10 19:14 UTC, olohr commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data-sheet.component.ts
> +    const name = `${this.personDetails.firstName} ${this.personDetails.surname}`;
This can be removed. If we implement some snack bar/toast system later, we can add it again

2021-09-21 16:28 UTC, Alfer-Star commented on src/WebUI/ClientApp/src/app/modules/member-management/member-details/member-data-sheet.component.ts
> +      this.showLoadingText = undefined;
Instead I did set showLoadingTest optional.

2021-09-21 16:28 UTC, merged